### ISSUE TITLE
Create Events page to match mockup

### ISSUE THREAD

**Issue by RyanRussell00** [UWB-ACM/uwbacm-site#273]
Create an Events page to match the mockup provided by the design team.

Feel free to use your own judgment to make decisions on the layout as needed.
Please confirm discrepancies with the design team and the rest of the website team.

**Comment by RyanRussell00** [comment]
Please add a link to the events page in the footer

**Comment by RyanRussell00** [comment]
Looks really good!
Just a few minor improvements:

1. There should be a way for users to interact with the "Weekly Events". Maybe link it to the contact page? Or have some text that says "join our mailing list for more info" or something.

2. The links for the "Community event" at the top don't work.

3. On mobile view the "Events Calendar" is much too cramped. Please change it's width/height to better fit on a mobile screen.

**Comment by mduw** [comment]
> Looks really good!
> Just a few minor improvements:
> 
>     1. "Weekly Events" is linked to the subscribe section in contact page.
> 
>     2. Broken links in "Community event" is fixed, except "Seminars". Not sure where to link it to.
> 
>     3. Responsive calendar added
