### ISSUE TITLE
Massive idling loading time for devices with low network connection (3G)

### ISSUE THREAD

**Issue by bpas247** [UWB-ACM/uwbacm-site#3]
I was investigating loading times for the website, and for some reason there's a significant loading time when I throttle the network conditions to 3G (using Chrome DevTools).

![capture](https://user-images.githubusercontent.com/18705892/45938330-d5961480-bf7d-11e8-9565-8e9590033102.PNG)

Notice that everything looks fine, except for the idling time. It seems to load anywhere between 7-12 seconds (sometimes taking as long as 24 seconds).

For comparison, here is the loading time for the UW-Blockchain website (hosted on an S3 bucket):
![capture](https://user-images.githubusercontent.com/18705892/45938372-31f93400-bf7e-11e8-98b3-814dc72c71c4.PNG)

And here is the loading time for my personal website (also hosted by GitHub-pages):
![capture](https://user-images.githubusercontent.com/18705892/45938403-74bb0c00-bf7e-11e8-9990-68a7e1580ad4.PNG)

What could be causing this?

**Comment by Chris-Johnston** [comment]
Some of profile images are massive, yet the `#officers .officer__avi-container` style is `130px` by `130px`. Odd that the chrome dev tools categorize downloading as 'Idle'.

![image](https://user-images.githubusercontent.com/16418643/45997781-9f2bc880-c055-11e8-9d21-87cc26d43e8e.png)

**Comment by Chris-Johnston** [comment]
webhook test pls ignore

**Comment by bpas247** [comment]
After merging #2 I can confirm that this issue still occurs:
![image](https://user-images.githubusercontent.com/18705892/46168432-5179b080-c24d-11e8-96ff-ba16f298cf65.png)

**Comment by Chris-Johnston** [comment]
I would recommend Firefox's network debugger for this. It looks like the images are not of consistent size still, some are much larger than others (which are slow to load), and some of the scripts are pretty huge too.

**Comment by bpas247** [comment]
Okay, used Firefox's network debugger and found something interesting:
![image](https://user-images.githubusercontent.com/18705892/46268554-f9160d80-c4ef-11e8-8220-307d955e3e59.png)

How could we improve the loading times for these components?

**Comment by bpas247** [comment]
Will need to do more testing if this issue is still relevant after #13. 

Closing it for now until further testing has been conducted.
