### ISSUE TITLE
Form Submissions Not Reaching Mailchimp

### ISSUE THREAD

**Issue by cforcomputer** [UWB-ACM/uwbacm-site#32]
I tried subscribing to the form on the live website, and unless there's a long delay on Mailchimp analytics, it wasn't getting the new contact.

I did use a different email to the one I subscribed with originally.

![image](https://user-images.githubusercontent.com/32972797/61180022-aa5cde80-a5fe-11e9-9dc4-30eeab2481b3.png)

**Comment by bpas247** [comment]
I feel like we can migrate our form submission code to use the [mailchimp api wrapper](https://www.npmjs.com/package/mailchimp-api-v3), although that would require setting up an environment variable. It would make error handling easier though.

**Comment by cforcomputer** [comment]
> although that would require setting up an environment variable

Not sure how to do that yet, but I can look into it.

**Comment by etcadinfinitum** [comment]
Well, our mailchimp account has no active API keys, so that's fun. Digging into this now, will hopefully have a fix out this weekend.

**Comment by bpas247** [comment]
https://github.com/UWB-ACM/uwbacm-site/blob/13d9e25967eaf97ee1a4d1bb6980e1874e0fdb08/src/pages/home/Form.jsx#L36-L42
So I just noticed that we never actually check the return status of the API endpoint, or anything that's being returned for that matter 🤔 we should definitely look into adding error handling here.

**Comment by etcadinfinitum** [comment]
A PR for this is forthcoming! As it turns out, Mailchimp doesn't like a body within its endpoint calls, and the values have to be embedded within the URL. (Mailchimp also doesn't like CORS, so jsonp is the way to go.) I'll tag Brady and Pat for a review so y'all can take a look at implementation details.
