### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by bpas247** [UWB-ACM/uwbacm-site#4]
We should minify the HTML that's deployed to production to improve loading times.

**Comment by Chris-Johnston** [comment]
I think that we should do this with a script. We'd also have to rename our human-readable `index.html` to be something else.

**Comment by bpas247** [comment]
Are there any js libraries that could help with this? I can't think of any that doesn't require a package manager.

We could probably rename `index.html` to `index-build.html`, or build the minified html file and deploy it on another branch (e.g. `gh-pages` branch).

**Comment by Chris-Johnston** [comment]
I don't think that deploying to another branch is a good idea. I think I've tried [this npm package](https://www.npmjs.com/package/html-minifier) before.

**Comment by bpas247** [comment]
Should we install node to the repo?

**Comment by Chris-Johnston** [comment]
No licensing issues, we just can't. GH pages only serves up static files (or files built by Jekyll), so we can't have any sort of back-end code running.

**Comment by kash** [comment]
The site loads up pretty quickly for me. Minifying the html wouldn't make the site any faster.

**Comment by bpas247** [comment]
@Chris-Johnston 
> GH pages only serves up static files (or files built by Jekyll), so we can't have any sort of back-end code running.

Could a package manager help manage our dependencies? I'm thinking we might be able to use something like [Bower](https://bower.io/) or [Yarn](https://yarnpkg.com/en/) to help install a package to minify HTML. This won't require any back-end code being implemented, since we just need it to produce a minified html file.

@kash
> The site loads up pretty quickly for me. Minifying the html wouldn't make the site any faster.

[Except minifying HTML can improve loading times](https://www.newmediacampaigns.com/blog/Why-Minify). This may also help improve #3, although I don't really expect it to close that issue. Either way, I consider it good practice to minify the HTML, CSS, and JS files on production builds.

**Comment by Chris-Johnston** [comment]
Sure, we could run a script (that uses node packages or really anything) to minify our files, but Kash is right. While minifying the HTML might have some performance benefits, the real bandwidth hog (only when throttling to 3G speeds) are the images that are still inconsistently sized.

I think minifying would not be worth the effort of implementation and maintenance.

**Comment by bpas247** [comment]
#13 Seems to have fixed this issue for us.
